#!/usr/bin/env php
<?php

// We have to set this global variable. Wordpress is not awesome.
$table_prefix = 'wp_';

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Wordpress Installer', '1.0.0');
$app->add(new Wordpress\Installer\Console\NewCommand);

$app->run();
